### ISSUE TITLE
2 column layout

### ISSUE THREAD

**Issue by jsta** [eddelbuettel/samples-rmarkdown-metropolis#2]
It is not currently possible to have a two-column layout with evaluated code chunks in Rmd beamer (see https://support.rstudio.com/hc/en-us/community/posts/202717656-Can-we-have-columns-in-rmarkdown-beamer-presentations-). I have used the solution [here](http://pandoc-discuss.narkive.com/T5tOc23J/two-column-layout-in-r-markdown-beamer) to some success:

_In your latex/beamer template preamble,_
```
\def\begincols{\begin{columns}}
\def\endcols{\end{columns}}
\def\begincol{\begin{column}}
\def\endcol{\end{column}}
```
_then_:

```
## Slide

\begincols

\begincol

``{r }
plot(1)
``
\endcol

\begincol

``{r }
plot(2)
``
\endcol

\endcols
```
Would this be a welcome addition to `header.tex`?

**Comment by eddelbuettel** [comment]
No, why?  I have been using the standard latex form for two colums in beamer for years, directly and with Rmd eg in metropolis.

But _you_ are free to create your own header.tex and add them to your liking, just like color choice, institute and other first-slide material and so on.

The operational term for the repo is _samples_.  It's a place for you to start from.

So I suggest we close this.  Ok?

**Comment by jsta** [comment]
Thank you for the response. I am glad I asked before submitting a PR. 

Are you able to run the following without error?

```
## Slide

\begin{columns}

\begin{column}{0.5\textwidth}

``{r }
plot(1)
``
\end{column}

\begin{column}{0.5\textwidth}

``{r }
plot(2)
``
\end{column}

\end{columns}

```

**Comment by eddelbuettel** [comment]
I don't mix markdown and latex within one block.  In essence, I start a new section from `\begin{columns}` to `\end{columns}` which contains only LaTeX.  AFAIK the only way to do this.  I don't think you can, and whether you define your aliases or not has nothing to do with it.

It is a pandoc / Rmarkdown / R interaction issue.

**Comment by momenezes** [comment]
Better late than never. I just found this solution in the bookdown book and thought it's worth sharing here. The link is: https://bookdown.org/yihui/rmarkdown-cookbook/multi-column-layout.html
And the code is:

`:::::: {.columns}

::: {.column width="55%" data-latex="{0.55\textwidth}"}
```{r, echo=FALSE, fig.width=5, fig.height=4}
par(mar = c(4, 4, .2, .1))
plot(cars, pch = 19)
```
:::

::: {.column width="5%" data-latex="{0.05\textwidth}"}
\ 

:::

::: {.column width="40%" data-latex="{0.4\textwidth}"}
The figure on the left-hand side shows the `cars` data.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
in reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur.
:::
::::::
`

It works like a charm in Rmarkdown with Beamer, and with Metropolis theme. 
Regards

**Comment by eddelbuettel** [comment]
It's a standard Pandoc feature also documented there.  I use it quite a bit.
