### ISSUE TITLE
Changing the frame style

### ISSUE THREAD

**Issue by TiagoVentura** [eddelbuettel/samples-rmarkdown-metropolis#3]
Hi, 

First, I loved your adaptation of metropolis fo rmarkdown. Thanks!

This might be a dumb question, but how do I change the style of the frame in markdown?  I want to reproduce the following code in rmarkdown

\begin{frame}[standout]
Thank you!
\end{frame}

Thank you!

**Comment by eddelbuettel** [comment]
You can actually mix and match, so I would just try a quick test document with three slides, and add that (as is) as a fourth.   Pandoc is really "just" a preprocessor, at the end of the day this is being fed to latex.

**Comment by eddelbuettel** [comment]
That did not work, but you can see here

- [here for mtheme / metropolis](https://github.com/matze/mtheme/issues/205)
- [here for pandoc](https://github.com/jgm/pandoc/issues/3007#event-711456707)

but the issue raised there holds: apparently it does not flip back from standout.

**Comment by TiagoVentura** [comment]
Perfect! It worked here, since it is my last slide, I didn't check how to flip back from standout
