### ISSUE TITLE
How to add a logo only to the title slide of the beamer in Rmarkdown?

### ISSUE THREAD

**Issue by ke-zhu** [eddelbuettel/samples-rmarkdown-metropolis#4]
Hi,

Your templet helps me a lot, thanks!

While I know that I can add a logo to every slide by `\logo{\includegraphics[width=.2\textwidth]{logo.png}}`, I want to add a logo only to the top right of *the title slide* like the presentations in your website. How could I do that?

Thank you!

**Comment by eddelbuettel** [comment]
See the metropolis documentation, I think I am using `\titlegraphic{}`.
